language: csharp
mono: none
dotnet: 2.2
dist: xenial
solution: Notionpad.sln
script:
 - dotnet build Notionpad.sln
 - dotnet test Tests/Notionpad.UnitTests/Notionpad.UnitTests.csproj
branches:
 only:
  - master
  - develop